---
title: "recipe book"
author: "Marie Bogena"
theme: vapor
format: qmd
--- 


You want to bake, you want to cook? But you have no idea where to look? Fresh cooking is an art, but it's also not super hard. This is a recipe book from grandmas for people who are not grandmas yet.

#Rafaello Muffins: Zubereitung
**1**
Für den Muffinteig *Eier, Zucker, Vanillezucker und Pflanzenöl* verrühren. Nach und nach *Mehl und Backpulver* dazu geben. *Kokosmilch und Amaretto* einrühren. *Kokosflocken* unterheben.

**2**
Muffinblech mit Papierförmchen auslegen. Hälfte des Teigs in die Förmchen geben, bis sie etwa zur Hälfte gefüllt sind. Je ein Raffaello in jede Teigmulde drücken. Mit dem restlichen Muffinteig bedecken. Im vorgeheizten Ofen bei 170 °C 25 Minuten backen.

**3**
In der Zwischenzeit für das Frosting Butter in einer Schüssel schaumig schlagen. In einem Topf 200 g Zucker und Kokosmilch zum Kochen bringen. Mehl einrühren. Sobald Creme eingedickt ist, Topf vom Herd nehmen und in die schaumige Butter einrühren. 30 Minuten in den Kühlschrank stellen.

**4**
Muffins aus dem Ofen nehmen, auskühlen lassen. Frosting in einen Spritzbeutel mit großer Lochtülle füllen. Raffaello-Muffins damit garnieren. Die Haube vorsichtig in Kokosraspel tunken. 
